name: cargo audit

on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1