on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  rust:
    name: Check
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install rust
          uses: dtolnay/rust-toolchain@stable
        - name: cache dependencies
          uses: Swatinem/rust-cache@v2
        - name: check formatting
          run: cargo fmt --all -- --check
        - name: cargo check
          run: cargo check --workspace --locked
        - name: clippy
          run: cargo clippy --all-targets --all-features

  test-plan:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: install rust
          uses: dtolnay/rust-toolchain@stable
        - name: cahce dependencies
          uses: Swatinem/rust-cache@v2
        - name: test
          run: cargo test
